name: Feature Request
description: General idea for improving the project
labels: ['enhancement']
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that our feature request form is appropriate for you.
      options:
        - label: My idea doesn't duplicate any existing Prismix functionality
          required: true
        - label: I believe that my idea falls into Prismix's scope and should be offered as part of Prismix built-in functionality
          required: true
  - type: textarea
    id: feature-purpose
    attributes:
      label: Feature purpose
      description: |
        Purpose of the feature - if it solves some problem, precise in particular which. If it benefits the program in some other way, precise in particular why.
        Present the underlying reason why this feature makes sense, and what is the context of it.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What would you like to see as a solution to the purpose specified by you above?
    validations:
      required: true
  - type: textarea
    id: why-existing-not-sufficient
    attributes:
      label: Why currently available solutions are not sufficient?
      description: |
        Evaluate the existing solutions in regards to your requirements.
        If something you're suggesting is already possible, then explain to us why the currently available solutions are not sufficient.
        If it's not possible yet, then explain to us why it should be.
    validations:
      required: true
  - type: dropdown
    id: help
    attributes:
      label: Can you help us with this feature idea?
      description: |
        Prismix is offered for free and our resources are limited.
        Helping us increases the chance of making it happen.
      options:
        - Yes, I can code the solution myself and send a pull request
        - Somehow, I can test and offer feedback, but can't code
        - No, I don't have time, skills or willings for any of that
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Everything else you consider worthy that we didn't ask for.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this feature request form.
